// AUTO-GENERATED by scripts/build-codelists.mjs from
// abf/extracted/field_codelists.md — do not edit by hand.
// 52 coded fields / 211 codes.
import type { CodeList } from "./codelists.ts";

export const CODE_LISTS: Record<string, CodeList> = {
  "BasicSystem": {
    prompt: "Briefly describe your system: for example...",
    codes: [
      { code: "1", phrase: "Standard" },
      { code: "2", phrase: "2/1" },
      { code: "3", phrase: "Acol" },
      { code: "4", phrase: "Precision" },
      { code: "5", phrase: "Strong club" },
      { code: "6", phrase: "Honeymoon Moscito" }
    ],
  },
  "CountType_NT": {
    prompt: "Against notrump contracts, how do you show count ?",
    codes: [
      { code: "1", phrase: "High-Low = Even" },
      { code: "2", phrase: "Low-High = Even" },
      { code: "x", phrase: "Not used" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "CountType_S": {
    prompt: "Against suit contracts, how do you show count ?",
    codes: [
      { code: "1", phrase: "High-Low = Even" },
      { code: "2", phrase: "Low-High = Even" },
      { code: "x", phrase: "Not used" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "DiscardType_NT": {
    prompt: "Against notrump contracts, how do you signal when discarding ?",
    codes: [
      { code: "1", phrase: "McKenney" },
      { code: "2", phrase: "Odd=ENCRG, Even=McKenney" },
      { code: "3", phrase: "Even=ENCRG, Odd=McKenney" },
      { code: "4", phrase: "Odd/Even" },
      { code: "5", phrase: "Low Encourage" },
      { code: "6", phrase: "High Encourage" },
      { code: "8", phrase: "Revolving" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "DiscardType_S": {
    prompt: "Against suit contracts, how do you signal when discarding ?",
    codes: [
      { code: "1", phrase: "McKenney" },
      { code: "2", phrase: "Odd=ENCRG, Even=McKenney" },
      { code: "3", phrase: "Even=ENCRG, Odd=McKenney" },
      { code: "4", phrase: "Odd/Even" },
      { code: "5", phrase: "Low Encourage" },
      { code: "6", phrase: "High Encourage" },
      { code: "8", phrase: "Revolving" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "Doubles_1": {
    prompt: "Which other Doubles and Redoubles do you use ? E.g.",
    codes: [
      { code: "1", phrase: "Support Doubles & Redoubles" },
      { code: "2", phrase: "Rosenkranz" },
      { code: "3", phrase: "Balancing" },
      { code: "4", phrase: "Lead-Directing" }
    ],
  },
  "Doubles_2": {
    prompt: "More details about your Doubles and Redoubles E.g.",
    codes: [
      { code: "1", phrase: "Support Doubles & Redoubles" },
      { code: "2", phrase: "Rosenkranz" },
      { code: "3", phrase: "Balancing" },
      { code: "4", phrase: "Lead-Directing" }
    ],
  },
  "FourHonourLead_NT": {
    prompt: "Against notrump contracts, which card do you lead from 4 or more headed by an honour card ?",
    codes: [
      { code: "4", phrase: "4th highest" },
      { code: "1", phrase: "attitude" },
      { code: "3", phrase: "3rd/Low" },
      { code: "5", phrase: "3rd/5th" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "FourHonourLead_S": {
    prompt: "Against suit contracts, which card do you lead from 4 or more headed by an honour card ?",
    codes: [
      { code: "4", phrase: "4th highest" },
      { code: "1", phrase: "attitude" },
      { code: "3", phrase: "3rd/Low" },
      { code: "5", phrase: "3rd/5th" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "FourNTOther": {
    prompt: "Describe your other uses of 4NT",
    codes: [
      { code: "1", phrase: "Natural" },
      { code: "2", phrase: "Quantitative" },
      { code: "3", phrase: "NAT, QUANT" }
    ],
  },
  "FourSmallLead_NT": {
    prompt: "Against notrump contracts, which card do you lead from four small cards ?",
    codes: [
      { code: "1", phrase: "TOP" },
      { code: "2", phrase: "2nd highest" },
      { code: "3", phrase: "3rd highest" },
      { code: "4", phrase: "4th highest" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "FourSmallLead_S": {
    prompt: "Against suit contracts, which card do you lead from four small cards ?",
    codes: [
      { code: "1", phrase: "TOP" },
      { code: "2", phrase: "2nd highest" },
      { code: "3", phrase: "3rd highest" },
      { code: "4", phrase: "4th highest" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "ImmedCueMajor": {
    prompt: "What is your immediate cue of a major suit opening ?",
    codes: [
      { code: "1", phrase: "5 other Major & 5 minor 6-10" },
      { code: "9", phrase: "natural" }
    ],
  },
  "ImmedCueMinor": {
    prompt: "What is your immediate cue of a minor suit opening ?",
    codes: [
      { code: "1", phrase: "Michaels 5/5 Majors 6-10" },
      { code: "9", phrase: "natural" }
    ],
  },
  "JumpOvercall": {
    prompt: "Briefly describe the method you use for a jump overcall in a suit",
    codes: [
      { code: "1", phrase: "weak" },
      { code: "3", phrase: "intermediate" },
      { code: "5", phrase: "strong" },
      { code: "9", phrase: "roman" }
    ],
  },
  "JumpRaiseMajor": {
    prompt: "Describe your jump raise of an opening bid of one in a major suit.",
    codes: [
      { code: "1", phrase: "Preempt 0-6 HCP, 5+ cards" },
      { code: "3", phrase: "Limit  10-12 HCP, 4+ cards" },
      { code: "4", phrase: "Limit  7-9 HCP, 4+ cards" },
      { code: "9", phrase: "Forcing" }
    ],
  },
  "JumpRaiseMinor": {
    prompt: "Describe your jump raise of an opening bid of one in a minor suit.",
    codes: [
      { code: "1", phrase: "Preempt 0-6 HCP, 5+ cards" },
      { code: "2", phrase: "Inverted: 6-9 HCP, 4+ cards" },
      { code: "3", phrase: "Limit  10-12 HCP, 4+ cards" },
      { code: "9", phrase: "Forcing" }
    ],
  },
  "LeadPartnersSuit_NT": {
    prompt: "How do you lead in partner's bid suit against NT contracts ? E.g. several of: Top of sequence [Ssx] Top of 2 [Xx] Low from 2 [xX] Top of 3 small [Xxx] Middle of 3 small [xXx] Honour doubleton [Hx] or",
    codes: [
      { code: "x", phrase: "!|As above" },
      { code: "1", phrase: "standard" },
      { code: "5", phrase: "Ssx Xx Xxx Hx hxX" }
    ],
  },
  "LeadPartnersSuit_S": {
    prompt: "How do you lead in partner's bid suit against suit contracts ? E.g. several of: Top of sequence [Ssx] Top of 2 [Xx] Low from 2 [xX] Top of 3 small [Xxx] Middle of 3 small [xXx] Honour doubleton [Hx] o",
    codes: [
      { code: "x", phrase: "!|As above" },
      { code: "1", phrase: "standard" },
      { code: "4", phrase: "Ssx Xx xXx Hx hxX" }
    ],
  },
  "MajorJumpShift": {
    prompt: "What do you show by a jump shift response to a major suit opening ?",
    codes: [
      { code: "1", phrase: "Natural, weak at 2 level" },
      { code: "2", phrase: "Fit showing: 5+ cards & 4 card support" },
      { code: "5", phrase: "Natural, game forcing" },
      { code: "9", phrase: "Splinter: 0-1 cards, 4+ card support" }
    ],
  },
  "MinorJumpShift": {
    prompt: "What do you show by a jump shift response to a minor suit opening ?",
    codes: [
      { code: "1", phrase: "Natural, weak at 2 level" },
      { code: "2", phrase: "Fit showing: 5+ cards & 4 card support" },
      { code: "5", phrase: "Natural, game forcing" },
      { code: "9", phrase: "Splinter: 0-1 cards, 4+ card support" }
    ],
  },
  "Open1C": {
    prompt: "Describe your 1C opening",
    codes: [
      { code: "1", phrase: "12+ HCP, !T3+!C" },
      { code: "2", phrase: "11+ HCP, !T2+!C" },
      { code: "9", phrase: "STRONG, 16+ HCP, any shape" }
    ],
  },
  "Open1D": {
    prompt: "Describe your 1D opening",
    codes: [
      { code: "2", phrase: "11+, !T2`+!D" },
      { code: "3", phrase: "11-20 HCP, !T3`+!D" },
      { code: "4", phrase: "11+ HCP, !T4`+!D" },
      { code: "8", phrase: "11+, better minor, 3`+!D" }
    ],
  },
  "Open1H": {
    prompt: "Describe your 1H opening",
    codes: [
      { code: "1", phrase: "12-20 HCP !T5+!H" },
      { code: "3", phrase: "11-22 HCP !T4+!H" },
      { code: "5", phrase: "11-15 HCP !T5+!H" },
      { code: "8", phrase: "10-15 HCP, 4+!H, <4!S" }
    ],
  },
  "Open1NT": {
    prompt: "Describe your 1NT opening",
    codes: [
      { code: "1", phrase: "12-14 Balanced" },
      { code: "2", phrase: "15-17 Balanced" },
      { code: "3", phrase: "16-18 Balanced" },
      { code: "4", phrase: "10-15 HCP, !T4+/4+ MAJORS" },
      { code: "5", phrase: "Any 20+" },
      { code: "6", phrase: "12-14 BAL,   14-16 BAL in 3!^rd!n seat" }
    ],
  },
  "Open1S": {
    prompt: "Describe your 1S opening",
    codes: [
      { code: "4", phrase: "11+ HCP, !T4`+!S" },
      { code: "5", phrase: "11-20 HCP, !T5`+!S" }
    ],
  },
  "Open2C": {
    prompt: "Describe your 2C opening",
    codes: [
      { code: "1", phrase: "11-15 HCP, 5+!C UNBAL" },
      { code: "2", phrase: "11-15 HCP precision style: 6+!C or 5!C & 4Major" },
      { code: "4", phrase: "23+ BAL or any game force" },
      { code: "6", phrase: "Any game force" }
    ],
  },
  "Open2D": {
    prompt: "Describe your 2D opening",
    codes: [
      { code: "1", phrase: "Weak, 6-9 HCP, 6+!D" },
      { code: "2", phrase: "Multi : weak Major OR 20-22 BAL" },
      { code: "3", phrase: "Weak Major" },
      { code: "9", phrase: "8 Playing tricks, 6+!D" }
    ],
  },
  "Open2H": {
    prompt: "Describe your 2H opening",
    codes: [
      { code: "1", phrase: "Weak, 6-10 HCP, 6!H" },
      { code: "2", phrase: "Multi : weak, 5+!H & 5 any other suit" },
      { code: "9", phrase: "8 Playing tricks, 6+!H" }
    ],
  },
  "Open2NT": {
    prompt: "Describe your 2NT opening",
    codes: [
      { code: "1", phrase: "20-22 balanced" },
      { code: "2", phrase: "minors: 5+!C&5+!D 6-9 HCP" }
    ],
  },
  "Open2S": {
    prompt: "Describe your 2S opening",
    codes: [
      { code: "1", phrase: "Weak, 6-10 HCP, 6!S" },
      { code: "2", phrase: "Multi : weak, 5+!S & 5 in either minor" },
      { code: "9", phrase: "8 Playing tricks, 6+!S" }
    ],
  },
  "Open3NT": {
    prompt: "Describe your 3NT opening",
    codes: [
      { code: "1", phrase: "Gambling, solid minor, no side A or K" },
      { code: "2", phrase: "27-28 Balanced" }
    ],
  },
  "Over1NTInterf": {
    prompt: "What method do you use after your opponents compete over your 1NT bid ? Does this apply when 1NT was not your opening bid ?",
    codes: [
      { code: "1", phrase: "lebensohl" },
      { code: "2", phrase: "rubinsohl" }
    ],
  },
  "Overcall1NT": {
    prompt: "What does you direct 1NT overcall mean ? i.e. in second seat",
    codes: [
      { code: "1", phrase: "15-17 BAL" },
      { code: "2", phrase: "15-18 BAL" },
      { code: "4", phrase: "Single suit takeout" },
      { code: "5", phrase: "Strong takeout" },
      { code: "6", phrase: "Two suited takeout" }
    ],
  },
  "Reopen1NT": {
    prompt: "What does your re-opening 1NT overcall mean ? i.e. in fourth seat. Also do you use sandwich 1NT after both opponents bid ?",
    codes: [
      { code: "1", phrase: "10-14" },
      { code: "5", phrase: "15-18" }
    ],
  },
  "Resp1NT2CStyle": {
    prompt: "What does your 2 club response to 1NT opening bid mean ? Add details if this varies by seat position or vulnerability.",
    codes: [
      { code: "1", phrase: "Simple Stayman" },
      { code: "2", phrase: "Extended Stayman" },
      { code: "5", phrase: "5 card Major enquiry" },
      { code: "8", phrase: "Game force relay" }
    ],
  },
  "Resp1NT2D": {
    prompt: "What is 2D response to 1NT ? Note that responses are no longer assumed to be transfers so you need to state which are transfers.",
    codes: [
      { code: "x", phrase: "Natural, To Play" },
      { code: "1", phrase: "Transfer !H" },
      { code: "8", phrase: "Forcing Stayman ?" }
    ],
  },
  "Resp1NT2H": {
    prompt: "What is 2H response to 1NT ? Note that responses are no longer assumed to be transfers so you need to state which are transfers.",
    codes: [
      { code: "x", phrase: "Natural, To Play" },
      { code: "1", phrase: "TRF !S" }
    ],
  },
  "Resp1NT2NT": {
    prompt: "What is 2NT response to 1NT ? Note that responses are no longer assumed to be transfers so you need to state which are transfers.",
    codes: [
      { code: "1", phrase: "Invite 3NT" },
      { code: "2", phrase: "TRF !D" }
    ],
  },
  "Resp1NT2S": {
    prompt: "What is 2S response to 1NT ? Note that responses are no longer assumed to be transfers so you need to state which are transfers.",
    codes: [
      { code: "x", phrase: "Natural, To Play" },
      { code: "1", phrase: "TRF minor" },
      { code: "2", phrase: "TRF !C" },
      { code: "7", phrase: "Range probe" },
      { code: "8", phrase: "Range Probe/TRF !C" }
    ],
  },
  "Resp1NTDoubled": {
    prompt: "Describe your methods when your 1NT opening is doubled. See also Over 1NT Interference in section 9.",
    codes: [
      { code: "0", phrase: "Same" },
      { code: "2", phrase: "Rubinsohl" },
      { code: "3", phrase: "Lebensohl" }
    ],
  },
  "RKCBStyle": {
    prompt: "RKCB response style:",
    codes: [
      { code: "1", phrase: "1430" },
      { code: "3", phrase: "3041" },
      { code: "9", phrase: "1430 exc.!C" }
    ],
  },
  "SeqLead_NT": {
    prompt: "Against notrump contracts, which style do you use when leading from sequences of honour cards ?",
    codes: [
      { code: "1", phrase: "Overlead All" },
      { code: "2", phrase: "Overlead except AKx(+)" },
      { code: "3", phrase: "Overlead, A-Attitude  K-Count" },
      { code: "4", phrase: "Underlead" },
      { code: "5", phrase: "Journalist" },
      { code: "6", phrase: "A-Attitude  K-Count" },
      { code: "7", phrase: "Slavinsky" },
      { code: "8", phrase: "Rusinow" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "SeqLead_S": {
    prompt: "Against suit contracts, what style do you use when leading from sequences of honour cards ? 7 : Slavi nsky",
    codes: [
      { code: "1", phrase: "Overlead All" },
      { code: "2", phrase: "Overlead except AKx(+)" },
      { code: "3", phrase: "Overlead, A-Attitude  K-Count" },
      { code: "4", phrase: "Underlead" },
      { code: "5", phrase: "Journalist" },
      { code: "6", phrase: "A-Attitude  K-Count" },
      { code: "8", phrase: "Rusinow" },
      { code: "9", phrase: "See Note #" }
    ],
  },
  "SignalDeclarerLead": {
    prompt: "What signals do you use when declarer leads a suit ?",
    codes: [
      { code: "1", phrase: "Count" },
      { code: "3", phrase: "Smith Echo in trumps" },
      { code: "9", phrase: "Prism hand pattern signal" }
    ],
  },
  "SignalPartnerLead_NT": {
    prompt: "Against notrump contracts, how do you signal on partners lead ? Use numbers for priorities.",
    codes: [
      { code: "1", phrase: "Low Encourage" },
      { code: "2", phrase: "High Encourage" },
      { code: "3", phrase: "Suit Preference" },
      { code: "4", phrase: "Count" },
      { code: "5", phrase: "Low = Even" },
      { code: "6", phrase: "Low = Odd" }
    ],
  },
  "SignalPartnerLead_S": {
    prompt: "Against suit contracts, how do you signal on partners lead ? Use numbers for priorities.",
    codes: [
      { code: "1", phrase: "Low Encourage" },
      { code: "2", phrase: "High Encourage" },
      { code: "3", phrase: "Suit Preference" },
      { code: "4", phrase: "Count" },
      { code: "5", phrase: "Low = Even" },
      { code: "6", phrase: "Low = Odd" }
    ],
  },
  "ThreeSmallLead_NT": {
    prompt: "Against notrump contracts, which card do you lead from three small cards ?",
    codes: [
      { code: "1", phrase: "Top" },
      { code: "2", phrase: "Middle" },
      { code: "3", phrase: "Bottom" }
    ],
  },
  "ThreeSmallLead_S": {
    prompt: "Against suit contracts, which card do you lead from three small cards ?",
    codes: [
      { code: "1", phrase: "Top" },
      { code: "2", phrase: "Middle" },
      { code: "3", phrase: "Bottom" }
    ],
  },
  "Transfers_1": {
    prompt: "Descrbe your methods after opponents use a transfer bid. E.g.",
    codes: [
      { code: "1", phrase: "Double = takeout" },
      { code: "2", phrase: "Cue = strong" },
      { code: "3", phrase: "Cue = good 2 suiter" },
      { code: "4", phrase: "Double = Lead-Directing" }
    ],
  },
  "UnusualNoTrump": {
    prompt: "What does your unusual leap in NT show ?",
    codes: [
      { code: "1", phrase: "minors" },
      { code: "2", phrase: "Other suits" },
      { code: "3", phrase: "Lower 2 unbid suits" },
      { code: "4", phrase: "2 non-touching suits" },
      { code: "5", phrase: "Any 2 unbid suits" }
    ],
  },
  "UnusualNT": {
    prompt: "Briefly describe your use of the Unusual NT convention. See also Conventions on the inside pages. If you need more space, please use selection 9. 5 : Any 2 unbid suits",
    codes: [
      { code: "1", phrase: "minors" },
      { code: "2", phrase: "Other suits" },
      { code: "3", phrase: "Lower 2 unbid suits" },
      { code: "4", phrase: "2 non-touching suits" },
      { code: "9", phrase: "!1!B!|See section 9!#y" }
    ],
  },
};
